nasal_feilretting = {'name': 'nasal_feilretting',
                     'areas': ['e_spoken',
                               'e_written',
                               'sw_spoken',
                               'sw_written',
                               'w_spoken',
                               'w_written',
                               't_spoken',
                               't_written',
                               'n_spoken',
                               'n_written'],
                     'rules': [{'pattern': '\\bM RNX0\\b',
                                'replacement': 'M AX0 RN',
                                'constraints': []},
                               {'pattern': '\\bM AX0 RNX0\\b',
                                'replacement': 'M AX0 RN',
                                'constraints': []},
                               {'pattern': '\\bNG RNX0\\b',
                                'replacement': 'NG AX0 RN',
                                'constraints': []},
                               {'pattern': '\\bNG AX0 RNX0\\b',
                                'replacement': 'NG AX0 RN',
                                'constraints': []}]}
