name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip pylint pytest pytest-cov mypy -r requirements.txt
    - name: Run pytest
      run: python -m pytest tests --cov=lexupdater --cov-report=term-missing:skip-covered
    - name: Check code with pylint
      run: python -m pylint lexupdater --reports=y
